### PR TITLE
added table Name as const at generated row.

### PR DESCRIPTION
**Pull request by dfaruque**

### CODE REVIEW

**Comment by dfaruque** [comment]
please wait to merge I have another commit.

**Comment by dfaruque** [comment]
Now it is ready to merge as my point of view.

**Comment by volkanceylan** [comment]
Is there a line ending change, shows like all lines changed

**Comment by dfaruque** [comment]
I have pressed Ctrl + K + D (format document) in VS. This might be the cause.

**Comment by dfaruque** [comment]
any way, I have tested the generator and it is working as expected.

**Comment by volkanceylan** [comment]
Please send this without any formatting / whitespace changes. A pull request should only contain what it changes.

**Pull request closed without merging**
