### PR TITLE
Sergen news 001

### PR DESCRIPTION
**Pull request by rolembergfilho**
Hey Volkan !

It's a really long time disappeared. So let's back!!!

I hope that you'll accept my ideas for Sergen:
- Fix ConnectionKey problem
- Added hability to add Placeholder attribute in XYZRow
- Fix the duplicated [ConnectionKey("") line

See ya!

### CODE REVIEW

**Comment by JohnRanger** [comment]
Hi rolembergfilho,

thanks for sharing this. Hopefully it will flow into sergen.

With Kind regards,

John

**Comment by rolembergfilho** [comment]
Thanks @JohnRanger .

I have a lot of improvements in my Serenity's forked, like:

1. Automate Replace Diacritic words in DisplayName attribute in XYZRow
2. Automate input fields Editor according column type, 
2.1. e.g. if a field is date, automate input DateEditor, if is time, input TimeEditor, and on...
3. Automate input some mask or Editor according column name
3.1 e.g. if a field have phone in name (like PhoneHome or HomePhone), o, automate input mask for phone. If a field have Email in name, automate input EmailEditor....
4. Automate input some typescript dialogs in XYZDialog.ts
4.1 Script to confirm save data before close 
4.1 If a field have UpdateDate or UpdateDateTime (some with Date or DateTime), automate input afterLoadEntity()  with ".valueAsDate = new Date();".
4.2. If a field is boolean type, automate input "this.form.FIELD.change(e =>...." in constructor, with Q.confirm script


all of these enhancement have options to turn on/off to generate script.

After all these time, I saw that @volkanceylan is tired to answer a same tipe of question again and again... And I did it in order to get the best practices in Serenity code.

But... not is all perfect.... I would like to get help in

1. to input replace function in Json and DataGrid, to make it configurable at run time (now it's hardcoded... in portuguese...)
2. to input Keywords in Editor Replaces (it's hardcoded too...)

Hope to you, @dfaruque, @marcobisio, @Estrusco, @VictorTomaili and more could help me in this new enhancements.

**Comment by volkanceylan** [comment]
Hi @rolembergfilho, next version of sergen will let you to use custom settings, custom templates, and even create extra files if you like.

I want to keep sergen as slim as possible, as any extra features people adds makes it harder for me to improve it.

Anyway if there are changes here that can't be handled with new templating system in sergen, we can discuss it.

**Comment by rolembergfilho** [comment]
Agree with you about the complexity of new features of Sergen.

What about create a new Sergen Project, only to deal these features?

My idea is get Original Sergen (like in beggining) dll and then improve with these new features in this new Sergen Project, named like Sergen's Advanced.

I think that i'll be usefull, specially for new users, in order to understand how to develop TS scripts, and more.

**Comment by volkanceylan** [comment]
Closing this as sergen now supports custom templates in a folder

**Pull request closed without merging**
