### PR TITLE
DeleteNonPresentLines for MasterDetailRelation

### PR DESCRIPTION
**Pull request by Estrusco**
Hi @volkanceylan 

In case that in master detail list are shown only some rows (by pre-filter in repository), when entity are updated all non showed rows are deleted. 

I added DeleteNonPresentLines to make possible to decide if keep non present lines.

### CODE REVIEW

**Comment by volkanceylan** [comment]
What if user wanted to delete one of present lines? Dont think this is right. Use FilterField and value properties.

**Comment by Estrusco** [comment]
mmm yes, this is a problem. In my case user cannot delete lines. 
I have complex test in filter, I'm not sure that FilterField and FilterValue can help me. Anyway now I try, thanks.
Also I can make another behavior

**Comment by volkanceylan** [comment]
What about adding those missing lines to new list before save?

**Comment by Estrusco** [comment]
Yes, this is what I initially thinked. 
Isn't best choice for me because this behavior are in several table. 
I think I create a personal behavior for this. For you, is there any contraindication in derive a behavior class from an existing behavior?

**Pull request closed without merging**
