### PR TITLE
added ability to generate multiple entities at a time

### PR DESCRIPTION
**Pull request by dfaruque**
I have not touched the existing. just added the left panel.
image

### CODE REVIEW

**Comment by volkanceylan** [comment]
Could we make it into another dialog, e.g. opened by a "Generate Multiple" button next to table name, so it could be less confusing. There only module name, permission key should be edited.

**Comment by dfaruque** [comment]
Great. or could we use tab-control instead?

**Comment by dfaruque** [comment]
where Entity Identifier, Table Name and Preview texbox could be placed in a tab and multiple table selection in another tab

**Comment by volkanceylan** [comment]
Yes, it should also work

**Comment by volkanceylan** [comment]
You may take generation options / files to bottom

**Comment by dfaruque** [comment]
image

**Comment by volkanceylan** [comment]
Looks great! Thanks.

**Pull request merged**
