### PR TITLE
Dynamic navigation items, remove single default category, add Vietnamese locales

### PR DESCRIPTION
**Pull request by DucThanhNguyen**
1. The default category "Properties" on PropertyGrid has no use if no category has been defined. It should be removed to make the grid popup dialog more tidy
2. I think developer (not end-user) should has ability to create dynamic navigation items based on user defined data. For example, they can add user defined folders as sub-navigation items of Inbox in Email module, or can eventually add organization structure to the navigation.
To archive this, just define a class like this:

```
    public class DynamicNavItems : IDynamicNavItems
    {
        public List<NavItem> NavItems
        {
            get
            {
                var items = new List<NavItem>
                {
                    new NavItem(8000, "Mail", "fa-envelope"),
                    new NavItem(8100, "Mail/Inbox", typeof(Pages.EmailController), "Inbox", "fa-inbox"),
                    new NavItem(8200, "Mail/Sent", "/Mail/Sent", null, "fa-envelope-o")
                };

                int i = 0;
                foreach (var folder in GetInboxFolders())
                {
                    i++;
                    items.Add(new NavItem(8100 + i, folder.Name, "Mail/Inbox?FolderId=" + folder.Id, null, "fa-folder"));
                }

                return items;
            }
        }
    }
```

3. Add Vietnamese locales

### CODE REVIEW

**Comment by DucThanhNguyen** [comment]
This dynamic navigation is optional and seamlessly merge with default attribute based navigation system. NavItem's constructor is very similar to NavigationMenu and NavigationLink attributes

**Comment by volkanceylan** [comment]
Thanks @DucThanhNguyen 

You should take check for categories before the loop for performance reasons. 

There is also a little issue by not using categories. When you are not using flex layout, you need to set height for dialog by setting .s-PropertyGrid .categories if there are categories, to make it not scroll category links on top. This change would break that. I may ignore this for now.

Please reuse NavigationItemAttribute, you may derive your NavigationItem class from those attributes if a separate class is really required. Avoid abbrevations like Nav. 

What about INavigationItemSource interface with a GetItems() method that returns a list of NavigationItem attributes? I'm not sure why you need an enum also for menu type.

**Comment by DucThanhNguyen** [comment]
OK @volkanceylan. I've renamed it to INavigationItemSource and reused NavigationItemAttribute. The code is now much more simple.

**Comment by volkanceylan** [comment]
Ok thanks. I'll change GetItems() to a method.

**Comment by volkanceylan** [comment]
Btw, do you also have texts for Serene, so we could add it as an option?

**Comment by DucThanhNguyen** [comment]
Yes, i'll add a pull request for Serene

**Comment by DucThanhNguyen** [comment]
Add images for wiki [Dynamic navigation items](https://github.com/volkanceylan/Serenity/wiki/Dynamic-navigation-items)

categoriesasdynamicnavigationitems

organizationstructureonnavigation

**Pull request merged**
