### PR TITLE
User preferences: quick filters

### PR DESCRIPTION
**Pull request by marcobisio**
Dear @volkanceylan,
I've added the quick filters support to the user preferences: it seems to be working fine :-)

Thanks
Bye

### CODE REVIEW

**Comment by volkanceylan** [comment]
Hi @marcobisio, thanks for request, but i'll have to implement this without using getQuickFilters(), because that method should be called once, and also user might create additional filters later so it might not match the ones on screen. Need to handle cases when there are multiple editors, e.g. range too.

Will keep this open so i'll remember to implement it soon.

**Comment by marcobisio** [comment]
Ok thank you very much!

Bye!

**Comment by volkanceylan** [comment]
Hi @marcobisio,

Sorry a bit (year :) late. Implemented this with baf4b942c2efd4025116295d57d4f1d57d6cbe7f, so closing the pull request

**Comment by marcobisio** [comment]
Ahahah don't worry @volkanceylan! Thank you very much for your time and your effort!

Bye

**Pull request closed without merging**
