### PR TITLE
Added Oracle dialect

### PR DESCRIPTION
**Pull request by dfaruque**

### CODE REVIEW

**Comment by volkanceylan** [comment]
First of all thanks for your take on this. You should rebase on master before pull requests as this pull request also contains references to your old changes about regions.

Also replace of @ with : in SqlHelper is a bit dangerous. If @ passes inside a string, this would change it too. See DatabaseReferenceReplacer for a bit safer way to replace text inside SQL.

**Comment by volkanceylan** [comment]
DatabaseCaretReferences.Replace method i mean

**Comment by dfaruque** [comment]
Can you please give a hint how to use 
DatabaseCaretReferences.Replace()
If I want to replace @ with :

**Comment by volkanceylan** [comment]
Ok remove replace code, and rebase. I'll handle that part myself.

**Pull request closed without merging**
