### PR TITLE
Masterdetail different idfield

### PR DESCRIPTION
**Pull request by hannesb**
Sometimes, it makes sense not to use the primary key field of the master table for a master detail relationship. For example if you have a field with a unique constraint on the master table (like a alphanumeric order number in the northwind orders table) and want the master detail relationship to use that field.

This extension of the MasterDetailRelationBehaviour adds this feature.

### CODE REVIEW

**Comment by volkanceylan** [comment]
I think that's a dangerous way to use master-detail relation, e.g. using a field that might change, and smells like a bad design.

Anyway, please change AltIdField to MasterKeyField and idField to masterKeyField and will merge this one.

**Comment by volkanceylan** [comment]
Build broken, you should change in other places as well

**Comment by hannesb** [comment]
Hmm compiles fine on my machine?!?

**Comment by hannesb** [comment]
Thanks for the merge. I really like to participate in this great project...

**Comment by ga5tan** [comment]
@hannesb is this supposed to work with MasterFields, that are empty? (ie no details)
cause it's crashing here in EntityGrid, saying "Object reference not set to an instance of object"

**Pull request merged**
