### PR TITLE
Added connection string provider

### PR DESCRIPTION
**Pull request by blojayble**
Hi.
Right now the only place to keep and provide connection strings is the default config file.
I wanted to make it a little bit more flexible. I'm not sure if you find that necessary, but I thought it could be useful in my projects.

### CODE REVIEW

**Comment by blojayble** [comment]
Oops, automatic build seems to have failed due to my use of null-conditional operator(?.).

**Comment by volkanceylan** [comment]
Are you sure you need this? SqlConnections already has a method to override / set a connection string

I avoid to use C# 6 for those who still might use older VS versions and add Serenity as a submodule

**Comment by blojayble** [comment]
While it's certainly not like I won't be able to live without it, I thought it could be a clean way of achieving that. But maybe not all that useful and for my specific needs though.

**Comment by volkanceylan** [comment]
Hmm i understand you wrote in VSGallery, i can merge this no problem, but i must repeat that it'll only solve %1 of what you are trying to do

**Comment by volkanceylan** [comment]
Here is what i did. A separate root application where you administer global settings and contains the actual web.config file, with location path="/customer1" etc to change connection string per sub application. Add a virtual app for every customer and add a location path with connection strings to root web.config. All these can be automated. All customer apps share an "instance", files, web.config etc. So you only have two apps to manage.

**Comment by blojayble** [comment]
Oh, sorry, I misunderstood you completely the first time you mentioned multiple instances.
Now it seems a whole lot more sensible, especially since all of it can be automated.

Given my little experience in this field, I could use some docs to help me get through this, especially the automation bit, is there anything you can recommend?

Big thanks, and sorry for bothering you.

**Comment by volkanceylan** [comment]
You can use appcmd, or IIS management API to create sub applications. Adding a new location path to web.config is about loading xml and modifying it. You should have a page in root application where you can add a subsite / modify it.

**Comment by volkanceylan** [comment]
Another option is for subapplication to check its url and set its connection strings based on customer sub path.

**Comment by blojayble** [comment]
I think I like the second option more, seems more flexible. And it's something I actually already tried to implement, but in different setup. Gotta take a good look at that IIS API.

Thanks once more, you were of great help.

**Pull request closed without merging**
