### PR TITLE
Aspnetcore+net46

### PR DESCRIPTION
**Pull request by isukces**
We've made another port of Serenity for AspNetCore + .NET Framewortk 4.6. Base code for this is .NET Core branch of your project. 
Serenity is great but our problem was to combine Serenity framework with third party sytem on full .NET Framework. From other side we wanted to get rid of System.Web and old ASP and switch to AspNetCore because of stability, performance and better, cleaner architecture.

All modifications are wrapped with compiler directives so they don't affect to original targets.
We have found that distinction of meaning of ASPNETCORE and COREFX directives in original code is not sharp. They are turned on (.net core) and off (.net 4.5) in common. We introduced third combination ASPNETCORE without COREFX directive.

### CODE REVIEW

**Comment by volkanceylan** [comment]
First of all thanks for sharing your work. It will take some time to review these changes, as i don't want to break compatibility with prior applications.

Here are some points to be discussed on a first look:

1. I especially didn't want to support full framework in Serene ASP.NET Core version. This would introduce one more environment for me to support, which i would like to avoid. Anyway, you could just change target framework in Serene .NET Core version, make a few changes in config and it should (theoretically) work on desktop framework.

2. COREFX means Serenity is running on .NET Core / .NET Standard, not Desktop framework. ASPNETCORE means it is using ASP.NET CORE which could run on both .NET Core / .NET Desktop. I don't think this should be changed. 

Only problem here is Serenity.Web which has dependency to System.Web if running on Desktop framework and ASP.NET Core libraries if running on .NET Core / Standard.

I see that you tried to handle this by making .NET 4.6 target ASP.NET Core. It could be a workaround but there might be a problem. If somebody who is using normal Serene, changes target framework to 4.6 from 4.5 (which some users do without knowing what it is), he will automatically be using ASP.NET Core, with which code in desktop Serene won't work at all. I don't want this to happen either.

3. ASP.NET Core v2 was going to ditch .NET Framework completely. Here is the boring issue:
https://github.com/aspnet/home/issues/2022

That was one of reasons i didn't want to support ASP.NET Core on full framework. Anyway, looks like that is not the case now (for now, a few months or MS will ditch support in v3 maybe?)

4. I would prefer to upgrade Serene (desktop version) to ASP.NET Core, without using .NET Core itself, but problem is even though i write an upgrade guide, there might be users who has very large apps that will take lots of changes, or has a strict dependency on legacy ASP.NET MVC / ASP.NET WebForms. I have some large apps that use both ASP.NET MVC / ASP.NET WebForms in same project for example.

5. So, because of i can't do 4 and i should avoid 2, one idea is to make two versions of Serenity.Web, one original which depends on ASP.NET MVC, one with a new name Serenity.WebCore etc. that depends on ASP.NET Core but could run on both CORE / Desktop framework, what do you think?

**Comment by isukces** [comment]
Thank you for taking your time to analyze the changes. 
I fully agree with your arguments. Backward compatibility is very important. 
Moreover nobody knows what MS will do with ASP.NET Core in next versions. Apparently they change decisions frequently. 
From other side ASP.Net Core on desktop framework can be considered as good intermediate step towards Core framework.
So I agree that separate library (or set of libraries when necessary) is good solution.

**Comment by volkanceylan** [comment]
Hi again, 

I tried to create a Serenity.Web.AspNetCore library on aspnetcore-desktop branch, that users should use instead of Serenity.Web when they want to use ASP.NET Core on full framework.

Unfortunately, this required too much changes in Serene AspNetCore version, and didn't go so well, i as configuration and many other things are different.

Were you able to make Serene .NET Core version work on your changes? Could you share your changes for me to understand what you did?

**Comment by isukces** [comment]
Thank you for your response. Yesterday I finished changes and the result of my work is a set of alternative nuget packages. Each package has 'Core' appendix in its name:
```
Serenity.Caching.Couchbase.Core.2.10.0.nupkg
Serenity.Caching.Redis.Core.2.10.0.nupkg
Serenity.CodeGenerator.Core.2.10.0.nupkg
Serenity.Core.Core.2.10.0.nupkg
Serenity.Data.Core.2.10.0.nupkg
Serenity.Data.Entity.Core.2.10.0.nupkg
Serenity.Services.Core.2.10.0.nupkg
Serenity.Web.Core.2.10.0.nupkg
```
Complete source code is available on my fork [https://github.com/isukces/Serenity/tree/aspnetcore+net46](https://github.com/isukces/Serenity/tree/aspnetcore+net46)  .

As you said changing `Serenity.Web` is not enought. For example `IConfigurationRepository` from `Serenity.Core` needs do be changed in order to swich internal implementation into `Microsoft.Extensions.Configuration.IConfiguration`. I realized that complete set of libraries should be created, beacause each requires some small changes. Some of new projects uses `NET46` directive. Now I think the name is not good and needs to be changed because it's not about dotnet framework wersion but about combination of AspnetCore+FullFramework ecosystems.

Compilation directives keeps existing two targets almost untouched and gives oportunity to introduce third targed without conflict. Some additional files were added like `AssemblyLoadContext` and `ConfigurationBinder`. In my opinion some MS nuget packages are incomplete. 

And finally `build.cake` file was adjusted. It can produce `*.Core.*.nupkg` packages beside other.

**Comment by volkanceylan** [comment]
Thanks. Sorry if i miss something but were you able to make Serene work after these changes? I can't see your Serene (template) source.

I think i can remove hard coded dependencies in Serenity.Core etc. through service locator. So, theorically only Serenity.Web +/- CodeGenerator will need a AspNetCore version.

**Comment by isukces** [comment]
I haven't created separate template. Just made sample project with existing core template and then replaced nuget packages.

**Comment by volkanceylan** [comment]
OK, check my aspnetcore-desktop branch in both Serene and Serenity for a working version with a few glitches that doesn't look hard to solve. I've abstracted away ConfigurationManager dependency and had to make just a few changes in Serene code.

**Comment by volkanceylan** [comment]
Latest Serene supports Asp.Net Core 2.0 on .NET Framework. Just change Target Framework to net461 in your Serene.csproj.

There is no Sergen package for net461 yet though, open Serenity.DotNet solution build, get executable and accompanying files from Serenity.CodeGenerator/bin/debug/dotnet-sergen.exe. Execute it in your project dir.

**Pull request closed without merging**
