### PR TITLE
Radio button now using prop("checked", true/false) instead of attr("checked")

### PR DESCRIPTION
**Pull request by Estrusco**
@volkanceylan 
I have made a correction in RadioButtonEditor.
Setting now use prop() instead of attr() becouse is more recommended, and with attr() I have a malfunction.

### CODE REVIEW

**Comment by volkanceylan** [comment]
I have already fixed that issue by using checked property of element directly, not sure if this is still required

**Comment by Estrusco** [comment]
I have the issue with 3.2.2 version. In which version is your fix?

**Comment by volkanceylan** [comment]
Dont remember, try latest or change log

**Comment by Estrusco** [comment]
OK. Log say in 3.3.10. I try and tell you, thanks :)

**Comment by Estrusco** [comment]
OK @volkanceylan with current version it's ok. Thank you, I close this request

**Pull request closed without merging**
