### PR TITLE
RadioButton Editor

### PR DESCRIPTION
**Pull request by Estrusco**

### CODE REVIEW

**Comment by Estrusco** [comment]
Usage:

```cs
[RadioButtonEditor(Labels = new string[] { "Radio1", "Radio2", "Radio3" })]
public String MyOptionWithRadioButtons { get; set; }
```

or 

```cs
[RadioButtonEditor(Labels = new string[] { "Radio1", "Radio2", "Radio3" })]
public Int32? MyOptionWithRadioButtons { get; set; }
```

result

**Comment by yetanotherlogonfail** [comment]
sorry if this sounds negative but why would you post this code if it does not compile?
Labels !!! does not exist
and why after spotting a brilliant option to be added to Serene is there not one example of a working radio button set for say 2 options Yes/No

**Comment by volkanceylan** [comment]
:) @yetanotherlogonfail, this is a pull request which is not merged. There is a RadioButtonEditor in Serenity, try typing it

**Comment by yetanotherlogonfail** [comment]
Volkan, 
Many thanks I enjoys your lovely country a few months ago,great place.
Yes I get Intellisense on RadioButtonEditor, but then I'm guessing the syntax

so is it: 
[RadioButtonEditor] = no
[RadioButtonEditor(EnumKey = xyz) ] = no
[RadioButtonEditor(EnumKey = xyz) ] = no
[RadioButtonEditor(ClassYearKind my enum name) ] = no 
[RadioButtonEditor( "Yes", "No") ]
... I could go on but been at it all day here guessing !

**Comment by Estrusco** [comment]
@yetanotherlogonfail 

[RadioButtonEditor(typeof(YourEnum))] where YourEnum in your case is

public enum YesNo
{
    No = 0,
    Yes = 1
}

Compilte and transform T4

**Pull request closed without merging**
