### PR TITLE
Added option to generate LookupEditor

### PR DESCRIPTION
**Pull request by rolembergfilho**
Hey @volkanceylan,

It's my first pull request, so I hope if I done all right!
If don't, apologize me :)

So, I added option to gerenate LookupEditor in Foreign Keys, and LookupScript before "public sealed class "

ps.: It's more easy to delete or comment undesired LookupEditor than create new lines...

### CODE REVIEW

**Comment by volkanceylan** [comment]
Hi @rolembergfilho, it looks fine, there are a few places i need to check though.

Also, i'm a bit worried about adding those attributes without first checking if related row has a LookupScript attribute. Yes, removing it would be easier for most, but some users don't read errors and report it is not working.

**Comment by rolembergfilho** [comment]
I'm thinking: What kind of problem if all classes comes with a  [LookupScript("")] attribute?

I did it in my project, and I didn't note a lack of performance in database or web server. Other way is: - - generate a textlist warning verify if class have LookupScript attribute
- verify, and if don't have, input LookupScript automattically in these classes.

In other side, I'm happy because my first pull request was ok!

I'm would like to submit these new features:
- generate placeholders or hints (for sql server only, getting from description field)

- generate advanced field from a pre-set list (example: if a field called file, and pre-set is configure that file is fileupload, so generate fileupload field)

- generate replace text fields (here in Brazil we have accentuation in some words, like informação. But, in SQL Server, we input a table columns like informacao. So, when we generate code, we catch some of these words and did a replace. In dialog or columns caption title,  it'll show informação). In my mind, i know that spanish language have this same problem. I think that other language have this same problem, like turkish or german or nordic language.

**Comment by dfaruque** [comment]
Thank you @rolembergfilho I am also thinking this way.

**Comment by rolembergfilho** [comment]
Hey @dfaruque, let's work together to improve Sergen more and more? @volkanceylan needs our help to seed Serenity more and more, and I think that Sergen is a powerfull start door to new users.

I have an existing code gerenator (using since 2004). It generates codes for VO, DAO and View in classic ASP.NET. Of couse Serenity is MVC, but I think that usefull to get the idea of these methods and insert into Sergen. One of these features is search table in combobox or listbox. 

What do you think?

**Comment by dfaruque** [comment]
@rolembergfilho agree. though it is a simple task to add a search functionality but it will be very useful. Go ahead...

**Pull request merged**
