### PR TITLE
Radio Button Editor

### PR DESCRIPTION
**Pull request by Estrusco**
Now one request for all files.

### CODE REVIEW

**Comment by Estrusco** [comment]
Usage:

```cs
[RadioButtonEditor(Labels = new string[] { "Radio1", "Radio2", "Radio3" })]
public Int32? MyOptionWithRadioButtons { get; set; }
```

or 

```cs
[RadioButtonEditor(Labels = new string[] { "Radio1", "Radio2", "Radio3" }, Values = new string[] { "A", "B", "C"})]
public String MyOptionWithRadioButtons { get; set; }
```

result

**Comment by volkanceylan** [comment]
Thanks Estrusco, just one question... Why labels and values are hardcoded? Why not use an enum / lookup? Isn't this writing too much inline? This is not so reusable and hard to localize. I might change it to lookup/enum myself, but i want to understand your reasons.

**Comment by Estrusco** [comment]
@volkanceylan , no particular reason. Only I did not think to do it, or how to do it :) 
With the enum will sure be better. 
Thanks

**Comment by volkanceylan** [comment]
Ok, i'll convert it to enum / lookup

**Comment by Estrusco** [comment]
Thank you very much

**Pull request merged**
