### PR TITLE
Oracle Integration into Sergen (using Oracle.ManagedDataAccess)

### PR DESCRIPTION
**Pull request by kilroyFR**
Requires following configuration (App.config) of sergen (use of Oracle.ManagedDataAccess nuget (last nuget version in this sample but any would work) as recommanded by Volkan on Serenity Guide) : 

 ```
 <system.data>
    <DbProviderFactories>
      <remove invariant="Oracle.ManagedDataAccess.Client" />
      <add name="ODP.NET, Managed Driver" invariant="Oracle.ManagedDataAccess.Client" description="Oracle Data Provider for .NET, Managed Driver" type="Oracle.ManagedDataAccess.Client.OracleClientFactory, Oracle.ManagedDataAccess, Version=4.122.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342" />
    </DbProviderFactories>
  </system.data>  
```

and check that the corresponding line is listed on MACHINE.CONFIG file (DbProviderFactories tag) :
`<add name="Oracle Data Provider for .NET" invariant="Oracle.ManagedDataAccess.Client" description="Oracle Data Provider for .NET" type="Oracle.ManagedDataAccess.Client.OracleClientFactory, Oracle.ManagedDataAccess, Version=4.122.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342" />`

### CODE REVIEW

**Comment by kilroyFR** [comment]
Closes requests #1523 and #1941

**Comment by dfaruque** [comment]
good

**Comment by volkanceylan** [comment]
Thanks, this seems like it might break a few other database type, e.g. change in size control, size is also applicable for decimal / numeric fields.

**Comment by volkanceylan** [comment]
@kilroyFR i applied some of changes manually on a09503837191cb1b0dad0b92e755b3babf82dc9b. Please check and let me know if work as i don't have Oracle installed atm.

**Pull request closed without merging**
