### PR TITLE
ForeignKeyAttribute: set "Id" as default primary field

### PR DESCRIPTION
**Pull request by dfaruque**
This is my preference. I will be happy if you merge this.
I prefer Id as primary key for all tables. So `ForeignKey("TableName", "Id")` here "Id" is optional to me.

### CODE REVIEW

**Comment by dfaruque** [comment]
I love to see codes as clean as possible.

**Comment by dfaruque** [comment]
sorry it should be. 
Everybody love to see codes as clean as possible.

**Comment by volkanceylan** [comment]
Sorry @dfaruque but i don't think this is so useful.

But you can write an attribute for your personal usage.

e.g.

```
public class FKAttribute(string table, string field = "Id") : ForeignKeyAttribute
   : base(table, field)
{
}
```

**Comment by dfaruque** [comment]
Ok. no problem. your suggestion seems more elegant to me. :)

**Pull request closed without merging**
