### PR TITLE
Giving a hint to fix "Specified cast is not valid." exception.

### PR DESCRIPTION
**Pull request by dfaruque**
this is very useful to identify (culprit!) field on row. specially if the row has so many fields.

### CODE REVIEW

**Comment by dfaruque** [comment]
Before
before

After 
after

**Comment by volkanceylan** [comment]
What about only catching cast exception and raising an error like:

Invalid cast exception while trying to set value of ABC field on XYZRow as object.

**Comment by dfaruque** [comment]
Thank you @volkanceylan for reviewing and replying such an important guidance.
I have changed according to your guidance.

**Comment by volkanceylan** [comment]
Thanks @dfaruque

**Comment by mustafalotiya** [comment]
I'm getting same issue "Specified cast invalid". 
I have updated project to latest serenity updates but I'm not getting detail error. 
Can some one please help me to add above changes (@dfaruque suggested) to my project. 

Thanks in Advance.
Thanks @volkanceylan for fantastic platform.

**Comment by dfaruque** [comment]
At my end it works as expected. Please check the version of the references specially Serenity.Data.Entity v>=3.3.14.0

**Comment by mustafalotiya** [comment]
thanks for reply @dfaruque 
Serenity.Data.Entity file is updated with version 3.3.15 but still it did not shows detail error.

**Comment by dfaruque** [comment]
try deleting your bin and obj folder. then rebuilt...

**Pull request merged**
