### PR TITLE
New decorators for dialog.

### PR DESCRIPTION
**Pull request by Estrusco**
@volkanceylan I have added some new decorators for dialog to hide buttons.
HideDelete, HideSave, etc.

### CODE REVIEW

**Comment by ms4hafiz** [comment]
Hi @Estrusco 
Thank you for the patch.

Can i use this decorator with my existing project as a patch?

**Comment by Estrusco** [comment]
Hi @ms4hafiz 

You can, but you have to copy Serenity.CoreLib.d.ts in your Scripts\typings\serenity\  and  Serenity.CoreLib.js in your Scripts\serenity dir. Also you have to minimize Serenity.CoreLib.js and copy the Serenity.CoreLib.min.js in Scripts\serenity dir.

If you can, I suggest you to wait taht Volkan checks this and than merge it in serenity.

**Comment by volkanceylan** [comment]
Thanks @Estrusco , but couldn't it be easier to override updateInterface:

```ts
updateInterface() {
    super.updateInterface();
    this.deleteButton.hide();
}
```

I think such attributes use cases are limited and would increase size of CoreLib.js folder, while i'm trying to make it smaller.

**Comment by Estrusco** [comment]
In my personal case there are several table that are not deletable or insertable by the user.
But for me I have created a base class to manage these dialogs. 

I create these decorators mainly becouse there are many users who open issues related to buttons, and I think that decorators are more friendly for beginner users.

Anyhow I'm according with you that the size of CoreLib must be smaller possible. 
Then if you think all this is not necessary, I can close this request.

Wait for you response master ;)

**Comment by JohnRanger** [comment]
Hi @Estrusco  and @volkanceylan 

I find this a very good improvement and it really would not take too much space within CoreLib - and would enforce your declarative programming style, Volkan:-)

With Kind regards,

John

**Comment by volkanceylan** [comment]
Thanks for all suggestions but for now i think we should close this, i may later think about a different solution. A wiki entry about hiding buttons should be nice and useful for now.

**Pull request closed without merging**
