### PR TITLE
TS definitions for Slick.* namespace moved to slickgrid.d.ts

### PR DESCRIPTION
**Pull request by wldkrd1**
Added ts definitions for Slick.Controls namespace, moved Slick.* definitions from Serenity.CoreLib.d.ts to slickgrid.d.ts

### CODE REVIEW

**Comment by volkanceylan** [comment]
I might be missing something but isn't slickgrid.d.ts comes from a nuget package? I don't modify nuget package contents.

**Comment by volkanceylan** [comment]
Hmm ok its not nuget package. But if we do this, need to release slickgrid.d.ts file too.

**Comment by wldkrd1** [comment]
No, you added slickgrid.d.ts to the typings folder as an empty file, and the content I populated it with I moved from your Serenity.CoreLib.d.ts file. I just verified that the SlickGrid nuget package does not include any d.ts definitions (it's javascript-only)

**Comment by volkanceylan** [comment]
And Serenity.CoreLib.d.ts is a generated file, not a source file. Source for them are in Serenity.Externals.Slick.ts so when i rebuild, they will come back.

**Comment by volkanceylan** [comment]
I want to leave SlickGrid related inside Serenity typescript source files, as we now have a pretty customized SlickGrid.

**Pull request closed without merging**
