### PR TITLE
replace tfPath with TFPath

### PR DESCRIPTION
**Pull request by wldkrd1**
tfPath doesn't change in this block; TFPath is what is intended

### CODE REVIEW

**Comment by volkanceylan** [comment]
Thanks, this is how blind coding works :)

**Comment by wldkrd1** [comment]
No worries, I appreciate your efforts. I see it performing the tf add command and I'm not seeing errors there but I don't see the file(s) added to the workspace. GenerateCSS() isn't performing an add or checkout before writing site.less and it looks like ProjectFileHelper.AddFileToProject() is exiting before it has a chance to write to the project file with the updates. I'll keep working at it.

**Comment by volkanceylan** [comment]
Ok i'll handle them too, missed that stream writer

**Comment by volkanceylan** [comment]
See latest commit for site.less, but i couldn't locate problem with AddFileToProject

**Comment by wldkrd1** [comment]
Ok, I think it's working...AddFileToProject was finding the file referenced in the csproj file so it was returning (as it should). But the project was modified in in memory so I wasn't seeing the changes. Usually VS tells me that the project changed on disk but it didn't this time. I'm now seeing the TF add and the files added to the workspace. I'll update with latest and verify it's working as expected.

**Comment by wldkrd1** [comment]
BTW, the reason you need to replace tfPath with TFPath is because if tfPath is null (and it is if you don't have it configured) then all the work you do in lines 205-220 to find the correct path is wiped out on line 223.

**Pull request merged**
