### PR TITLE
Style change to Dialogs.

### PR DESCRIPTION
**Pull request by gguadalupe**
Hi Volkan!
For your consideration, I made some changes to the Alerts and Warnings to look like the last change you made.
Instead of images, I'm using the FontAwesome icons.

Warning! I'm not a web developer. I have REALLY BASIC css skills (crossing my fingers I did not break anything!)

I hope you like it!

Thank you!

Gus.

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

### CODE REVIEW

**Comment by volkanceylan** [comment]
Thanks, it looks fine to me, just not sure about alert icon and a few colors might change, but generally ok.

**Comment by volkanceylan** [comment]
And please don't change lines with @media (min-width: 768px)  etc rules

**Comment by gguadalupe** [comment]
I notice the change in the @media after I finish publishing the change. I compare the changes but didn't see any change. May be the GitHub editor changing non-visible chars? I also notice the editor ate the last line feed.

Let me know if you want to change something! I will be pleased to help any way I can!

Thank you!

Gus.

**Comment by biggikalli** [comment]
I'm sorry for intruding. But I think its time for "The Accountant"! Yeaaa, not the ordinary candidate on this matter but it's a fetish of mine and I have a strong opinion on this style proposal. I absolutely agree with Gustavo's ideas, "Bye bye Lollipop"I like the changes but maybe possible for further refinement before accepting the commit. Many users of web apps are used to and might like the shiny buttons with shadows & gradients, seems glamorous to some.To be clear; I have had no issue with Serenity's template and it continues to serve all my apps and users.This thread just made me notice and think about this for the very first time. Still a huge fact, these 3d-ish elements are rapidly fading away and soon they may become oldish. But as The Maestro mentioned; conflict & error free CSS is a must. Also, color choice and icons sets are critical for success and long lasting success. Gus, are you open for a dialog with me about color palettes and icon sets?I'm a novice in CSS but still able to change what & when needed on my sites without the risk of conflicts. I totally agree with you and think this is a fantastic discussion. Just let me know if you are interested. I'm open. Regards, BiggiOn Dec 8, 2017 5:54 PM, Gustavo Guadalupe <notifications@github.com> wrote:I notice the change in the @media after I finish publishing the change. I compare the changes but didn't see any change. May be the GitHub editor changing non-visible chars? I also notice the editor ate the last line feed.
Let me know if you want to ange something! I will be pleased to help any way I can!
Thank you!
Gus.

**Comment by gguadalupe** [comment]
Hey @biggikalli! Sure thing! I did try to keep the same look & feel from the AdminLTE template.
Shoot me an email with your ideas and maybe I can be of help!

Gus.

**Comment by dfaruque** [comment]
looks nice

**Comment by volkanceylan** [comment]
I've applied changes in this pull request manually. We probably also need to think about using Bootstrap alerts for better mobile compatibility, but that's for another day. Thanks, closing.

**Comment by volkanceylan** [comment]
Hey @biggikalli, nice to see you are back, please try latest commit (after release) and if there are style changes you'd like to make, i'd be pleased to try them.

**Pull request closed without merging**
