### PR TITLE
Added DisplayProperty and UrlProperty to UrlFormatter

### PR DESCRIPTION
**Pull request by wldkrd1**
This allows you to optionally specify the column which contains the target URL and/or the link text for the UrlFormatter. Current version uses ctx.Value for both.

### CODE REVIEW

**Comment by volkanceylan** [comment]
Shouldn't url and display html encoded?

**Comment by wldkrd1** [comment]
Good grief, bad copy/paste into the editor. Sorry about that...one sec.

**Comment by volkanceylan** [comment]
Also is there a missing using? AppVeyor failing.

**Comment by volkanceylan** [comment]
Thanks a lot

**Pull request merged**
