### PR TITLE
specify location for button's separator

### PR DESCRIPTION
**Pull request by minhhungit**
Add ability to specify location of button's separator

### CODE REVIEW

**Comment by volkanceylan** [comment]
Thanks @minhhungit, what about making 

separator?: false | true | "right" | "both"

instead of adding a secondary option?

**Comment by minhhungit** [comment]
>separator?: false | true | "right" | "both"

I think only one option with 'false' - 'left' - 'right' and 'both' is okay,
I will update it

**Comment by minhhungit** [comment]
or only separator?: 'right'|'both'
null = false

**Comment by minhhungit** [comment]
Updated
```javascript
 separator?: (false | true | 'left' | 'right' | 'both');
```

@volkanceylan Please review it

**Comment by volkanceylan** [comment]
Yes, need "true" for backward compability

**Pull request merged**
