### PR TITLE
Fix some mistakes in Vietnamese translation

### PR DESCRIPTION
**Pull request by DucThanhNguyen**

### CODE REVIEW

**Comment by volkanceylan** [comment]
Thanks @DucThanhNguyen. Could you next time start from latest commit? It shows like you have 15 commits now.

**Comment by DucThanhNguyen** [comment]
It because I reverted some commits and add some pull requests myself to update my folk with the latest Serenity. Not sure it's right way as I've never used Github before. By the way, I can't update my folk of Serene with yours. There're conflicts, and most of them can be resolved easily in Visual Studio, but there on item called Serenity can be resolved as shown in the image below:
error-merger-serene

If I choose "Keep Source" or "Keep Target", it show the top error message. "Compare Files" shows the popup dialog.

What is the best way to keep my folk up to date with your code?

**Comment by volkanceylan** [comment]
I recommend using GitExtensions, other tools tries to make Git look like TFS or SVN, but its not

**Comment by DucThanhNguyen** [comment]
OK Thanks!

**Pull request merged**
